---
version: 2

models:
  - name: product_information_silver
    description: "Transformed product information"

    columns:
      - name: prd_id
        data_type: INT
        tests:
          - unique
          - not_null

      - name: cat_id
        data_type: TEXT
        tests:
          - not_null

      - name: prd_key
        data_type: TEXT
        tests:
          - not_null

      - name: prd_nm
        data_type: TEXT
        tests:
          - not_null

      - name: prd_cost
        data_type: INT
        tests:
          - _is_integer_or_null

      - name: prd_line
        data_type: TEXT
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Mountain', 'Road', 'Other Sales', 'Touring', 'n/a']

      - name: prd_start_dt
        data_type: DATE
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
          - _is_less_than_or_equal_to:
              compare_to: prd_end_dt

      - name: prd_end_dt
        data_type: DATE
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

      - name: dwh_create_date
        description: "Date when the record was created in the data warehouse"
        data_type: TIMESTAMP
