---
version: 2

models:
  - name: product_categories_silver
    description: "Transformed data for product categories and subcategories"
    columns:
      - name: id
        description: "Unique identifier"
        data_type: TEXT
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: cat
        description: "Category"
        data_type: TEXT
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: subcat
        description: "Subcategory"
        data_type: TEXT
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: maintenance
        description: "Maintenance information"
        data_type: TEXT
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Yes', 'No']

      - name: dwh_create_date
        description: "Date when the record was created in the data warehouse"
        data_type: TIMESTAMP
